# MacBookPro16,1 speaker-only DSP configuration.
# Based on lemmyg/t2-apple-audio-dsp commit b5c5a136 (2026-07-31).

monitor.alsa.rules = [
    {
        matches = [
            {
                api.alsa.card.name = "Apple T2 Audio"
                node.name = "~alsa_output.pci.*.HiFi__Speaker__sink"
                media.class = "Audio/Sink"
            }
        ]
        actions = {
            update-props = {
                audio.allowed-rates = [48000, 44100]
                node.name = "alsa_output.platform-sound.RawSpeakers"
                node.description = "Raw Speaker Device (do not use)"
                node.nick = "RawSpeakers"
                node.pause-on-idle = false
                session.suspend-timeout-seconds = 0
            }
        }
    }
]

node.software-dsp.rules = [
    {
        matches = [
            { node.name = "alsa_output.platform-sound.RawSpeakers" }
        ]
        actions = {
            create-filter = {
                filter-path = "/usr/share/t2-linux-audio/16_1/graph.json"
                hide-parent = true
            }
        }
    }
]

wireplumber.components = [
    {
        name = /usr/share/t2-linux-audio/16_1/t2-force-unmute.lua, type = script/lua,
        provides = custom.t2-audio
    }
]

wireplumber.profiles = {
    main = {
        node.software-dsp = required
        custom.t2-audio = required
    }
}
